Add required package dependency libsqlite3-dev
SQLite 3 development files are needed in order to successfully install
ooni-backend.
Error message while installing 'pip install -r requirements.txt'
'src/connection.h:33:21: fatal error: sqlite3.h: No such file or
directory'